### PR TITLE
Add Docker Blog Post

### PR DESCRIPTION
**Pull request by Gituser143**

### CODE REVIEW

**Comment by Gituser143** [comment]
@anihm136 I had to resolve some merge conflicts which involved your blog post. Can you verify that there was no mess up?

**Comment by Gituser143** [comment]
@anihm136 I had to resolve some merge conflicts which involved your blog post. Can you please verify that there was no mess up?

**Review by tfidfwastaken — APPROVED** [review]
It looks right to me, and pretty much ready for our blog. Great work @Gituser143 @metonymic-smokey 

I'll be merging, we'll fix it up if anything else is missing.

**Review by tfidfwastaken — APPROVED** [review]

**Comment by anihm136** [comment]
I don't see any issues either, it's all good

**Comment by tfidfwastaken** [comment]
@Gituser143 @metonymic-smokey 
Tagging you both because there is a *major* omission here. You forgot to credit yourselves :smile: 

You need to add authorship data to `authors.yml`, and update the front matter on this post.

Have a look at [this](https://tianqi.name/jekyll-TeXt-theme/docs/en/authors) and 4b1f6fa4fce8b292c771f7f6b4f973291dd9c6e0 for pointers.

Also add `show_author_profile: true` to the front matter, something @anihm136 and I overlooked last time. (I fixed that right now)

Also I realized, I am not sure if this theme supports multiple authors on a post.
for now try something like,
```
author: author1 and author2
```

**Comment by Gituser143** [comment]
Woops. @tfidfwastaken we'll fix it asap.

**Pull request merged**
