### PR TITLE
Add post "How Linux made me a better developer"

### LINKED ISSUE #33: [BLOG POST] How Linux made me a better developer
# Title:
How Linux made me a better developer

# Abstract:
When a Linux user says that Linux is best for developers, it is often unclear to other non-linux users what improvements and benefits it offers over other OS's, specially when they have all the tooling set up and find it hard to migrate. This post aims to describe, objectively, what improvements I experienced as a programmer after making the switch

### PR DESCRIPTION
**Pull request by anihm136**
Fixes #33 
Finally got around to doing this. It's a little wordy I feel, so any advice on how it can be made shorter/more readable is appreciated

### CODE REVIEW

**Comment by tfidfwastaken** [comment]
Nah I don't find it wordy, in fact the I like the style of this post. Just tell me when you want me to merge it.

**Comment by anihm136** [comment]
Yeah I think it's ready. I moved all the notes into footnotes except the first. I also rebased the branch off master, so there shouldn't be any issues merging

**Comment by tfidfwastaken** [comment]
Something looks fishy :fish: :tropical_fish: . Your PR was to `pesos/blogposts` instead of `pesos/master`. After changing the base to `pesos/master` I see that there are conflict markers on the file `authors.yml`. Can you remove those?

**Comment by anihm136** [comment]
I guess there's some mismatch between branches. I didn't want to push directly to master, so I pushed to blogposts instead, which I'd created when we started updating the blog. I did rebase it off master, but I guess I missed something. I'll clear it up in a bit

**Pull request merged**
