### PR TITLE
Add post 'Living in the terminal'

### LINKED ISSUE #32: [BLOG POST] Living in the terminal
# Title:
Living in the terminal

# Abstract:
A small list and introduction to popular command-line applications for daily tasks. Currently covers editors,file browsers, email and music

### PR DESCRIPTION
**Pull request by anihm136**
Fixes #32 
I'd like a review on this post and feedback on any improvements / additions that can be made. Feel free to mention any sections/applications that can be added

### CODE REVIEW

**Comment by tfidfwastaken** [comment]
Hi here's my personal feedback on the post.
I think the main thing you can improve is by trying to be more persuasive. I'm assuming your post targets people who aren't using terminal-based programs yet. If I were one of those people, I will need more convincing than just *knowing* about the terminal based options.

What's your reason for you to prefer these terminal-based programs over the GUI counterparts?   Is there some novel workflow it enables, that you can give an example of?  
Why do I need Vim and Emacs in the terminal over my current $EDITOR?  
I think your example with the music players did this pretty well, like the hotkeys feature, although I would still like having that explained more.

You mention that the terminal is faster and more efficient, but giving concrete examples will sell that point better with the audience you are presumably targeting with this post.

I also think adding a few screenshots in between to support your post would make it great.

This blog idea is excellent and I feel making those changes will make it really reach that potential and polish.

**Comment by anihm136** [comment]
Thanks for the feedback! I'll add some info about how they fit into my workflow to give a better idea of that

**Comment by tfidfwastaken** [comment]
Hey also don't forget to add yourself as an author in `_data/authors.yml`.

Follow [this](https://tianqi.name/jekyll-TeXt-theme/docs/en/authors) guide and add whatever plugs you have.

Then change the front matter from `author: true` to `author: yourname`.

**Comment by anihm136** [comment]
I've added a bit about my workflow and benefits. I'm not sure if its very convincing, mainly because explaining my entire setup could be a post by itself, but I think it's enough to encourage new users to try them out and decide for themselves. @tfidfwastaken Let me know if you think it's ready.

**Comment by tfidfwastaken** [comment]
Yes, this is what I felt the post needed!

I think we can merge this :)

**Pull request merged**
